version: "3"
services: 
    site:
        image: postgres
        container_name: "pg_container"
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=test_db
        ports: 
            - "5432:5432"
        volumes: 
            - "./db:/var/lib/postgresql/data/"

    bi:
        #image: metabase/metabase #maquinas x86
        image: kontinuity/metabase-arm64v8-with-drivers:latest #Arm e M1
        ports: 
            - "3000:3000"
        links: 
            - site


